name: Workflow for latest image

on:

  push:
    branches:
      - main
    paths:
      - '3.7-arm64/**'

  pull_request:
    branches:
      - main
    paths:
      - '3.7-arm64/**'

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: make 3.7 arm64