name: Build and push Multi-Architecture Docker Images for CRUX

on:
  push:
    branches:
      - main  # Trigger builds on push to the main branch (you can change this as needed)
  pull_request:
    branches:
      - main  # Trigger builds on PR to the main branch (you can change this as needed)

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner
    strategy:
      matrix:
        version: [2.6, 3.7, 3.7-updated ] # List of versions
        arch: [amd64, arm64, armhf] # List of architectures (amd64, arm64, armhf)
        variant: [core, setup, slim] # List of variants

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Disable sudo password prompt
        run: |
          echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/$USER

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for multi-platform builds
        with:
          use-new-buildx: true  # Use the latest version of Buildx

      - name: Set up Docker QEMU for ARM emulation
        uses: docker/setup-qemu-action@v2  # Set up QEMU to allow ARM emulation
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7  # Enable support for amd64, arm64, and armhf

      - name: Log in to DockerHub
        uses: docker/login-action@v2  # Log in to DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username (from GitHub Secrets)
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password/token (from GitHub Secrets)

      - name: Check if directory exists and build Docker image
        run: |
          # Determine the platform
          case "${{ matrix.arch }}" in
            "amd64") platform="linux/amd64" ;;
            "arm64") platform="linux/arm64" ;;
            "armhf") platform="linux/arm/v7" ;;
          esac

          folder="${{ matrix.version }}-${{ matrix.arch }}-${{ matrix.variant }}"

          # Check if the folder exists (and is not a symlink)
          if [ -d "$folder" ] && [ ! -L "$folder" ]; then

            # Prepare required files
            bash prepare-files.sh $folder || exit 1

            # Get additional tags
            additional_tags=""
            find . -type l -exec basename {} \; | while read l; do
              d=$(readlink -f $l); d=$(basename $d)
              if [ "${d}" == "${folder}" ]; then
              additional_tags="${additional_tags} -t sepen/crux:${l}"
              fi
            done

            echo "Building and pushing Docker image..."

            # Create and use the buildx builder instance
            docker buildx create --use

            # Build the image for selected platforms and push it
            set -x
            docker buildx build \
              --platform ${platform} \
              -f "$folder/Dockerfile" \
              -t sepen/crux:${folder} -t ${additional_tags} \
              --push $folder
          fi

      - name: Logout from DockerHub
        run: docker logout  # Log out from DockerHub to clean up authentication details
